name: Build and run test
description: 'Build and run test'
inputs:
  npm_token:
    required: true
    description: NPM token
  swagger_folder:
    required: true
    description: Swagger folder
runs:
  using: 'composite'
  steps:
    - name: Build test image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: test
        target: installer
        load: true

    - name: Run test
      shell: bash
      run: |
        docker run --rm \
        -v  ${{ inputs.swagger_folder }}:/s3_swagger_upload/ \
        --entrypoint "" \
        test bash -c "
        yarn --frozen-lockfile &&
        yarn tsc &&
        yarn build &&
        yarn test &&
        yarn lint --quiet"
        echo ${{ inputs.swagger_folder }}
        echo $PWD/s3_swagger_upload/
