name: Pull Request Check #Workflow name
on: #trigger
  workflow_dispatch:
  pull_request:
    types: ['opened', 'synchronize'] #create or update PR
    branches:
      - 'development'
      - 'release/**'
      - 'master'
    paths-ignore: #if the changes only in the following files, the workflow will not be triggered
      - '**/CHANGELOG.md'
      - '**/package.json'
jobs:
  main: #Job names
    environment:
      name: ${{ github.base_ref == 'master' && 'production' || contains(github.base_ref,'release') && 'staging' || 'development' }}
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run test
        uses: ./.github/actions/build-and-run-test